dataset: ['mnist']
params:
 bs_test: 200
 bs_train: 10
 epochs: 100
 lr: 0.005
dataset: ['emnist']
params:
 bs_test: 200
 bs_train: 10
 epochs: 150
 lr: 0.005
---
dataset: ['cifar10', 'cifar100']
params:
 bs_test: 200
 bs_train: 50
 epochs: 100
 lr: 0.01
 model: cnn
